sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L https://git.io/ejPSng | /bin/sh"

env:
  - METEOR_RELEASE=1.3.5.1
# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
