name: Build and Deploy

on:
  push:
    branches: [ build ]  # Adjust branch(es) to trigger builds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Adjust OS if needed

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Set executable bit for entrypoint.sh
        run: chmod +x docker/entrypoint.sh
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image (replace with your details)
        run: |
          docker build -t meetprolv/meetpro:latest . 

      - name: Push Docker image to registry (optional)
        run: docker push meetprolv/meetpro:latest
